### ISSUE TITLE
cell.getPhoneNumber() returns blank

### ISSUE THREAD

**Issue by MrGraversen** [sparkfun/MG2639_Cellular_Shield#16]
Hello,

I'm trying to run the code specified in the `MG2639_GetInfo.ino` example.

The code runs just fine except no phone number is returned. The status returned **[right here](https://github.com/sparkfun/SparkFun_MG2639_Cellular_Shield_Arduino_Library/blob/master/examples/MG2639_GetInfo/MG2639_GetInfo.ino#L121)** is 253.

I'm using a Danish sim card, if it matters. The phone number format is `11223344`.

There are no talk about this problem at all, so I'm at a loss.

**Comment by MrGraversen** [comment]
Bumping to see if anyone will help.

**Comment by MrGraversen** [comment]
Bumping again to see if anyone will help.

**Comment by anandbaskaran** [comment]
I think no one is available for us. Are you still looking for solution?

**Comment by MrGraversen** [comment]
Yes, I am.

**Comment by anandbaskaran** [comment]
Sorry for the late reply. I will look into this issue when I get some time in next week..

**Comment by MrGraversen** [comment]
I assume this issue was never looked into.

**Comment by loricrotser** [comment]
Hello! 

Since we have retired this product, I'm closing this issue. If you still need help with this product, you can also check in our forums [here](https://forum.sparkfun.com/).

Please do let us know if you have any more questions. 

Thank you!
