### ISSUE TITLE
Arduino 1.6.7 warning

### ISSUE THREAD

**Issue by i-make-robots** [sparkfun/MG2639_Cellular_Shield#17]
WARNING: Category '' in library SparkFun MG2639 CellShield is not valid. Setting to 'Uncategorized'

**Comment by couilloux** [comment]
I have the same issue when I try the simple MG2639_GetInfo. 

Any suggestion?

**Comment by loricrotser** [comment]
Hello! 

Since we have retired this product, I'm closing this issue. If you still need help with this product, you can also check in our forums [here](https://forum.sparkfun.com/).

Please do let us know if you have any more questions. 

Thank you!
