### ISSUE TITLE
GPRS UDP

### ISSUE THREAD

**Issue by anandbhaskaran** [sparkfun/MG2639_Cellular_Shield#18]
I am trying to use GPRS UDP with sparkfun. But I see that this is still in TO-DO. By when can I expect this to be done?

**Comment by loricrotser** [comment]
Hello! 

Since we have retired this product, I'm closing this issue. If you still need help with this product, you can also check in our forums [here](https://forum.sparkfun.com/).

Please do let us know if you have any more questions. 

Thank you!
