### ISSUE TITLE
HTTP REQUEST

### ISSUE THREAD

**Issue by n3mu** [sparkfun/MG2639_Cellular_Shield#19]
So I try to edit the sample codes to " GET /test.php?fn=test HTTP/1.1\nHost: mysite.com\n\n"
It runs but it doesn't pass the 'fn' and I also try POST with HTTP headers and again it doesn't work, Anyone who have try to do HTTTP request before?

**Comment by loricrotser** [comment]
Hello! 

Since we have retired this product, I'm closing this issue. If you still need help with this product, you can also check in our forums [here](https://forum.sparkfun.com/).

Please do let us know if you have any more questions. 

Thank you!
