### ISSUE TITLE
BUG: Missing "return"

### ISSUE THREAD

**Issue by tatobari** [sparkfun/MG2639_Cellular_Shield#20]
Line 108 of `MG2639_Cellular_Shield/Libraries/Arduino/src/SFE_MG2639_CellShield.cpp` should be:

`return begin(TARGET_BAUD_RATE);`

Instead of:

`begin(TARGET_BAUD_RATE);`

Otherwise, you can't know if the communication with the shield was successful because `0` is returned if nothing is specified.

**Comment by loricrotser** [comment]
Hello! 

Since we have retired this product, I'm closing this issue. If you still need help with this product, you can also check in our forums [here](https://forum.sparkfun.com/).

Please do let us know if you have any more questions. 

Thank you!
